### ISSUE TITLE
Generations are lost in Firefox and TOR Browser

### ISSUE THREAD

**Issue by davidmef** [aqualxx/stable-ui#5]
I have tried to use https://aqualxx.github.io/stable-ui/ from Firefox 109.0 (64-bit). I set a prompt, configure and submit. The job gets in the queue, is served, the image is gathered but it does not show. The canvas becomes blank. The Firefox error log shows:

> Uncaught 
> Object { _e: Error, name: "DatabaseClosedError", message: "InvalidStateError A mutation operation was attempted on a database that did not allow mutations.\n InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.", inner: {…}, stack: "" }
[index.b86d4f2f.js:66:2432](https://aqualxx.github.io/stable-ui/assets/index.b86d4f2f.js)
> Uncaught (in promise) TypeError: b is undefined
    m https://aqualxx.github.io/stable-ui/assets/index.b86d4f2f.js:591
    p https://aqualxx.github.io/stable-ui/assets/index.b86d4f2f.js:591
    c https://aqualxx.github.io/stable-ui/assets/index.b86d4f2f.js:591

Thinking that some of the browser addons may be interfering, I try in plain TOR Browser 12.0.2 (based on Mozilla Firefox 102.7.0esr) (32-bit) and it fails again. The error log shows:
> Uncaught 
> Object { _e: Error, name: "DatabaseClosedError", message: "InvalidStateError A mutation operation was attempted on a database that did not allow mutations.\n InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.", inner: {…}, stack: "" }

 > _e: Error: 
​
> inner: Object { _e: Error, name: "InvalidStateError", message: "A mutation operation was attempted on a database that did not allow mutations.\n InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.", … }
​
> message: "InvalidStateError A mutation operation was attempted on a database that did not allow mutations.\n InvalidStateError: A mutation operation was attempted on a database that did not allow mutations."
​
> name: "DatabaseClosedError"
>​ stack: ""
>​ <prototype>: Object { stack: "", … }
> index.b86d4f2f.js:66:2432

> Uncaught (in promise) TypeError: b is undefined
    m https://aqualxx.github.io/stable-ui/assets/index.b86d4f2f.js:591
    p https://aqualxx.github.io/stable-ui/assets/index.b86d4f2f.js:591
    c https://aqualxx.github.io/stable-ui/assets/index.b86d4f2f.js:591
index.b86d4f2f.js:591:1918
    p https://aqualxx.github.io/stable-ui/assets/index.b86d4f2f.js:591
    c https://aqualxx.github.io/stable-ui/assets/index.b86d4f2f.js:591
    InterpretGeneratorResume self-hosted:1422
    AsyncFunctionNext self-hosted:632

This error started to happen on Friday 27, I guess.

Since several days earlier, another error happens in which the generated images were displayed, but they did not appear in https://aqualxx.github.io/stable-ui/images

It works in Chrome, though. Can you fix it for Firefox and TOR Browser?

Thanks for your work.

**Comment by xcdmcode** [comment]
Experienced the same issue, but using the Brave mobile browser. Unfortunately no logs available, but it was on a request for a batch of 20 1024x1024 generations. Tokens were correctly subtracted from my balance but had the same result as OP.

**Comment by davidmef** [comment]
What happens now is that, after the image is generated, it remains as:

> Generation Status
Pending: 0 - Processing: 0 - Finished: 1 - Restarted: 0
Queue Position: 0
indefinitely.
Pressing Cancel does nothing.

The error in the console log is:

> Uncaught 
Object { _e: Error, name: "DatabaseClosedError", message: "InvalidStateError A mutation operation was attempted on a database that did not allow mutations.\n InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.", inner: {…}, stack: "" }
​
_e: Error: 
​
inner: Object { _e: Error, name: "InvalidStateError", message: "A mutation operation was attempted on a database that did not allow mutations.\n InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.", … }
​
message: "InvalidStateError A mutation operation was attempted on a database that did not allow mutations.\n InvalidStateError: A mutation operation was attempted on a database that did not allow mutations."
​
name: "DatabaseClosedError"
​
stack: ""
​
<prototype>: Object { stack: "", … }
​​
constructor: function r(i, o)
​​
stack: ""
​​
<prototype>: Object { stack: "", … }
[index.dc558922.js:66:2432](https://aqualxx.github.io/stable-ui/assets/index.dc558922.js)
    cC https://aqualxx.github.io/stable-ui/assets/index.dc558922.js:66

The Images tab is empty.

**Comment by anonderpling** [comment]
Likely to be fingerprinting protection, it interferes with canvas iirc

**Comment by davidmef** [comment]
I noticed now that it works when in normal browsing. In Firefox private mode, it fails when it tries to store the result.

> Inserting outputs into database 
Array [ {…} ]
[index.0554bfbb.js:66:12693](https://aqualxx.github.io/stable-ui/assets/index.0554bfbb.js)
Uncaught (in promise) 
Object { _e: Error, name: "DatabaseClosedError", message: "InvalidStateError A mutation operation was attempted on a database that did not allow mutations.\n InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.", inner: {…}, stack: "" }

I thought it might be related to an earlier message
> Persisted storage granted: false
but in normal browsing I also get this persisted storage message and the result image is visible.

**Comment by aqualxx** [comment]
Looks like Firefox private browsing is the culprit - this mode [doesn't support IndexedDB yet](https://bugzilla.mozilla.org/show_bug.cgi?id=1639542). In the meantime, I've added a message for those experiencing similar errors. Thank you!
