### ISSUE TITLE
Downloaded Images ZIP contains almost only zero bytes images

### ISSUE THREAD

**Issue by LastZolex** [aqualxx/stable-ui#8]
Hi all,

since yesterday's changes concerning the image pages, I experience problems when downloading images in my (Chrome-based) Opera browser.  It worked perfectly before though.

The ZIP file now contains all json parameter files and all png files, but only the json files look ok. The png files are often of zero bytes, but not always.

What happend before was that I experienced a browser crash when the changes were published, so it might be a problem only on my side.
Does it make sense to reset all my local storages to try to get up and running smoothly again or do others experience the same problem?

Thanks in advance for your efforts :) 

LZ

UPDATE #1: 
I just realized, that if I request ZIP files of smaller size (in my case less than 40 images) all images which were missing before are downloaded properly... strange.

UPDATE #2:
I tested it thoroughly, I can download **up to 49 pictures without problems** in one file. If I request more than that, I get all others as zero bytes images, no matter how many I want to download in the zip.
Unfortunately **50 is the pagesize for a maximum non-continuous page**, so I cannot even download one page at a time if I set the page size to 50. 
But maybe this is a clue to the cause of the issue? I cannot believe that it is pure coincidence ;)

**Comment by aqualxx** [comment]
Thanks for the report! The zero byte images + browser crash while downloading should now be fixed in the latest commit.

**Comment by LastZolex** [comment]
Fantastic, thank you very much for the quick fix! :) 
Now downloading a larger amount of generated images works smoothly again!!
